---
title: "joint meeting figures"
author: "Brendan F. Miller"
date: "10/31/2022"
output: html_document
---

```{r}

setwd("/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/")
figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/joint_meeting_figs/"

```

```{r}

## load in the functions for this pipeline
source(file = "../R/functions.Rmd")

```

```{r}

## initialize circle params

locs <- list(
  c(0.5, 0.5)
  )

cts <- list(
  list(outer = "B", inner = c("C"))
  )

probs <- list(
  list(outer = c(1), inner = c(1))
  )

## background params
s <- 10000
cb <- c("A")
pb <- c(1)

# note that the simulation starts on 0-1 scale but is scaled to 0-3100 in function simulate_circles
# can treat these values like microns

## outer ring approx 0.01 or 3100um = 31 micron width
## inner approx 868 microns across (3100*0.28)
rads <- replicate(4, list(outer = 0.15, inner = 0.14), simplify=FALSE)
pos_30 <- simulate_circles(simulate_background(size = s, cts = cb, prob = pb),
                        locs, radii = rads, cts, probs)
pos_30$id <- 30

## outer ring approx 0.03 or 3100um = 93 micron width
## inner approx 744 microns across (3100*0.24)
rads <- replicate(4, list(outer = 0.15, inner = 0.12), simplify=FALSE)
pos_90 <- simulate_circles(simulate_background(size = s, cts = cb, prob = pb),
                        locs, radii = rads, cts, probs)
pos_90$id <- 90

## outer ring approx 0.05 or 3100um = 155 micron width
## inner approx 620 microns across (3100*0.20)
rads <- replicate(4, list(outer = 0.15, inner = 0.10), simplify=FALSE)
pos_150 <- simulate_circles(simulate_background(size = s, cts = cb, prob = pb),
                        locs, radii = rads, cts, probs)
pos_150$id <- 150

## outer ring approx 0.10 or 3100um = 310 micron width
## inner approx 310 microns across (3100*0.10)
rads <- replicate(4, list(outer = 0.15, inner = 0.05), simplify=FALSE)
pos_300 <- simulate_circles(simulate_background(size = s, cts = cb, prob = pb),
                        locs, radii = rads, cts, probs)
pos_300$id <- 300

## outer ring approx 0.13 or 3100um = 403 micron width
## inner approx 124 microns across (3100*0.04)
rads <- replicate(4, list(outer = 0.15, inner = 0.02), simplify=FALSE)
pos_400 <- simulate_circles(simulate_background(size = s, cts = cb, prob = pb),
                        locs, radii = rads, cts, probs)
pos_400$id <- 400


pos_1circle_sizes <- dplyr::bind_rows(list(
  pos_30,
  pos_90,
  pos_150,
  pos_300,
  pos_400
))

pos_1circle_sizes$id <- factor(pos_1circle_sizes$id, ordered = TRUE, levels = c("30", "90", "150", "300", "400"))

```

```{r}

do.call(rbind, lapply(unique(pos_1circle_sizes$id), function(id){
  t <- table(pos_1circle_sizes[pos_1circle_sizes$id == id,"type"])
  t/sum(t)
}))

```

```{r}

s <- 10000
cb <- c("A", "B", "C")
pb <- c(0.928, 0.0407, 0.0313)

random_bg <- simulate_background(size = s, cts = cb, prob = pb, scale = 3100)

```

```{r}

dat <- pos_1circle_sizes[pos_1circle_sizes$id == "300",]
ggplot2::ggplot(data = dat) +
  ggplot2::geom_point(ggplot2::aes(x = x, y = y, color = type), size = 0.2) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::coord_equal() +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide3_circle.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

ggplot2::ggplot(data = random_bg) +
  ggplot2::geom_point(ggplot2::aes(x = x, y = y, color = type), size = 0.2) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::coord_equal() +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide3_random.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

```

```{r}

dat <- pos_1circle_sizes[pos_1circle_sizes$id == "300",]
ggplot2::ggplot(data = dat) +
  ggplot2::geom_bar(ggplot2::aes(x = type, y = (..count..)/sum(..count..), fill = type), color = NA) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::labs(x = "", y = "fraction", fill = "cell type")
ggplot2::ggsave(filename ="slide3_circle_bar.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

ggplot2::ggplot(data = random_bg) +
  ggplot2::geom_bar(ggplot2::aes(x = type, y = (..count..)/sum(..count..), fill = type), color = NA) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::labs(x = "", y = "fraction", fill = "cell type")
ggplot2::ggsave(filename ="slide3_random_bar.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

```

```{r}

dat <- pos_1circle_sizes[pos_1circle_sizes$id == "300",]

ggplot2::ggplot(data = dat[dat$x > 1150 & dat$x < 1550 & dat$y > 1150 & dat$y < 1550, ]) +
  ggplot2::geom_point(ggplot2::aes(x = x, y = y, color = type), size = 3) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::coord_equal() +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide4_circle_local.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

ggplot2::ggplot(data = dat[dat$x > 900 & dat$x < 2100 & dat$y > 900 & dat$y < 2100, ]) +
  ggplot2::geom_point(ggplot2::aes(x = x, y = y, color = type), size = 2) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::coord_equal() +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide4_circle_farther.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

```


dist 100
ring size 300
resolutions
300, 500, 900, 1200, 1500, 3000


```{r}

dat <- pos_1circle_sizes[pos_1circle_sizes$id == "300",]

pos <- dat[,c("x", "y")]
celltypes <- dat$type
cells <- sp::SpatialPointsDataFrame(
  coords = as.data.frame(pos),
  data=data.frame(
    celltypes=celltypes
    #name=rownames(pos)
))
cells <- sf::st_as_sf(cells)
sf::st_agr(cells) <- "constant"


resolutions <- c(300, 500, 900, 1200, 1500, 3000)
dat_shuffledCells <- makeShuffledCells(cells = cells, resolutions = resolutions, perms = 1, ncores = 7, seed = 1, verbose = TRUE)

```

```{r}

r <- 300
grid <- sf::st_make_grid(cells, cellsize = r)

ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid) +
  ggplot2::geom_sf(data = cells, ggplot2::aes(color = celltypes), size = 0.2) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_full_300.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

randomcells_300 <- cells
randomcells_300$celltypes <- dat_shuffledCells$`300`$`1`
sf::st_agr(randomcells_300) <- "constant"

ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid) +
  ggplot2::geom_sf(data = randomcells_300, ggplot2::aes(color = celltypes), size = 0.2) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_full_random_300.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")


i <- 60

int_real <- sf::st_intersection(cells, grid[[i]])
ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid[[i]]) +
  ggplot2::geom_sf(data = int_real, ggplot2::aes(color = celltypes), size = 3) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_grid60_real_300.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

int_random <- sf::st_intersection(randomcells_300, grid[[i]])
ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid[[i]]) +
  ggplot2::geom_sf(data = int_random, ggplot2::aes(color = celltypes), size = 3) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_grid60_random_300.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

```

```{r}

buffer_300 <- sf::st_buffer(cells[cells$celltypes == "C",], 100)

int_real <- sf::st_intersection(buffer_300, grid[[i]])
ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid[[i]]) +
  ggplot2::geom_sf(data = int_real, ggplot2::aes(color = celltypes), size = 3) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
# ggplot2::ggsave(filename ="slide5_grid60_real_300.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

# int_random <- sf::st_intersection(randomcells_300, grid[[i]])
# ggplot2::ggplot() +
#   ggplot2::geom_sf(data = grid[[i]]) +
#   ggplot2::geom_sf(data = int_random, ggplot2::aes(color = celltypes), size = 3) +
#   ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
#   ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
# ggplot2::ggsave(filename ="slide5_grid60_random_300.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")


```



```{r}

r <- 500
grid <- sf::st_make_grid(cells, cellsize = r)

ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid) +
  ggplot2::geom_sf(data = cells, ggplot2::aes(color = celltypes), size = 0.2) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_full_500.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

randomcells <- cells
randomcells$celltypes <- dat_shuffledCells$`500`$`1`
sf::st_agr(randomcells) <- "constant"

ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid) +
  ggplot2::geom_sf(data = randomcells, ggplot2::aes(color = celltypes), size = 0.2) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_full_random_500.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")


i <- 24

int_real <- sf::st_intersection(cells, grid[[i]])
ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid[[i]]) +
  ggplot2::geom_sf(data = int_real, ggplot2::aes(color = celltypes), size = 3) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_grid24_real_500.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

int_random <- sf::st_intersection(randomcells, grid[[i]])
ggplot2::ggplot() +
  ggplot2::geom_sf(data = grid[[i]]) +
  ggplot2::geom_sf(data = int_random, ggplot2::aes(color = celltypes), size = 3) +
  ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
  ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
ggplot2::ggsave(filename ="slide5_grid24_random_500.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

```

```{r}

# r <- 900

for(r in c(900, 1200, 1500, 3000)){
  
  grid <- sf::st_make_grid(cells, cellsize = r)

  ggplot2::ggplot() +
    ggplot2::geom_sf(data = grid) +
    ggplot2::geom_sf(data = cells, ggplot2::aes(color = celltypes), size = 0.2) +
    ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
    ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
  ggplot2::ggsave(filename = paste0("slide5_full_", r, ".pdf"), path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")
  
  randomcells <- cells
  randomcells$celltypes <- dat_shuffledCells[[as.character(r)]]$`1`
  sf::st_agr(randomcells) <- "constant"
  
  ggplot2::ggplot() +
    ggplot2::geom_sf(data = grid) +
    ggplot2::geom_sf(data = randomcells, ggplot2::aes(color = celltypes), size = 0.2) +
    ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
    ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
  ggplot2::ggsave(filename = paste0("slide5_full_random_", r, ".pdf"), path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")
  
}




# i <- 9
# 
# int_real <- sf::st_intersection(cells, grid[[i]])
# ggplot2::ggplot() +
#   ggplot2::geom_sf(data = grid[[i]]) +
#   ggplot2::geom_sf(data = int_real, ggplot2::aes(color = celltypes), size = 3) +
#   ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
#   ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
# ggplot2::ggsave(filename ="slide5_grid10_real_500.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")
# 
# int_random <- sf::st_intersection(randomcells, grid[[i]])
# ggplot2::ggplot() +
#   ggplot2::geom_sf(data = grid[[i]]) +
#   ggplot2::geom_sf(data = int_random, ggplot2::aes(color = celltypes), size = 3) +
#   ggplot2::scale_color_manual(values = c("A" = "#F8766D", "B" = "#00B81F", "C" = "#00A5FF")) +
#   ggplot2::guides(color = ggplot2::guide_legend(title = "cell type"))
# ggplot2::ggsave(filename ="slide5_grid10_random_500.pdf", path = figpath, device = "pdf", dpi = 600, width = 4, height = 3, units = "in")

```


```{r}

rezs <- c(300, 500, 900, 1200, 1500, 3000)

dat <- results_all_circles_melt[results_all_circles_melt$dist == 100 & results_all_circles_melt$ring_size == "300" & results_all_circles_melt$perc_A == 0.928,]
dat <- dat[dat$resolution %in% rezs,]

plotTrends_tmp(results = dat, idcol = "dist", figPath = paste0(figpath, "slide5_trends_dist100_pts_5.pdf"),
            width = 12, height = 12)

```

```{r}

#' @param idcol if results are a data.frame, this is the column that contains the additional feature to plot multiple trend lines with
#' by default it is 'id', which would be the name given to the column describing each list after melting together into a single dataframe
#' using `meltResultsList()`
#' @param ... additional plotting parameters for base R plotting. Fed into "lines()" in script
plotTrends_tmp <- function(results, idcol = "id", figPath = "results.pdf", width = 8, height = 8, legend = TRUE, ...){
  
  
  ## setup to check if original list output from `findTrends`, and plot one way
  ## or if a melted dataframe with ids from merging multiple trend analyses, check if dataframe and plot that way
  
  ## if in original list format from `findTrends`:
  if(inherits(results, "list")){
    message("results detected to be a list")
    
    pdf(figPath, width=width, height=height)
    par(mfrow=c(length(names(results)), length(names(results))),
        mar=rep(4,4))
    
    ## for each reference cell type, ie a dataframe in the list..
    sapply(names(results), function(ct1) {
      # print(ct1)
      results.norm <- results[[ct1]]
      results.norm[is.nan(results.norm)] <- NA
      results.norm[is.infinite(results.norm)] <- NA
      
      ## for each neighbor cell type...
      sapply(colnames(results.norm), function(ct2) {
        rg <- max(abs(results.norm[, ct2]), na.rm = TRUE)
        resolutions <- rownames(results.norm)
        
        ## instantiate a plot and plot trend
        plot(resolutions, results.norm[,ct2],
             type="l", lwd = 2,
             main=paste0(ct1,' ref \n', ct2, " neighbors"),
             ylim=c(-rg, rg),
             xlab="resolution", ylab="Z", ...)
        
        ## threshold lines
        abline(h = -2, col='red')
        abline(h = 2, col='red')
      })
    })
    dev.off()
    
    ## if a melted dataframe,
    ## will have an additional column that can serve to plot
    ## several trend lines on the same plot instance
    ## for example, ref vs neigh at different distances
  } else if(inherits(results, "data.frame")){
    message("results detected to be a data.frame")

    refs <- unique(results[,"reference"])
    neighs <- unique(results[,"neighbor"])
    ids <- unique(results[,idcol])
    
    cl <- rainbow(length(ids))
    
    pdf(figPath, width=width, height=height)
    par(mfrow=c(length(refs), length(neighs)),
        mar=rep(4,4))
    
    ## for each reference cell type...
    sapply(refs, function(ct1) {
      # print(ct1)
      results.norm <- results[results[,"reference"] == ct1,]
      results.norm[is.nan(results.norm[,"Z"]), "Z"] <- NA
      results.norm[is.infinite(results.norm[,"Z"]), "Z"] <- NA
      
      ## for each neighbor cell type...
      sapply(neighs, function(ct2) {
        results.norm.neigh <- results.norm[results.norm[,"neighbor"] == ct2,]
        
        yl <- max(abs(results.norm.neigh[, "Z"]), na.rm = TRUE)
        xl <- max(as.numeric(results.norm.neigh[,"resolution"]))
        
        ## instantiate a plot
        plot(0, 0, type = "n",
             main=paste0(ct1,' ref \n', ct2, " neighbors"),
             ylim=c(-yl, yl),
             xlim=c(0, xl),
             xlab="resolution", ylab="Z")
        
        ## for each id param, draw a line on plot instance
        for(i in 1:length(ids)){
          id <- ids[i]
          
          results.norm.neigh.id <- results.norm.neigh[results.norm.neigh[,idcol] == id,]
          
          points(as.numeric(results.norm.neigh.id[,"resolution"]), results.norm.neigh.id[,"Z"],
                pch=19, lwd=2, col=cl[i], ...)
        }
        
        ## threshold lines
        abline(h = -2, col='red')
        abline(h = 2, col='red')
        if(legend){
          legend("topleft", legend = ids, col=cl, pch=20, cex=0.5, title = "ids")
        }
      })
    })
    dev.off()
    
  } else {
    stop("`results` are neither a list from `findTrends` or a melted data.frame from `meltResultsList`")
  }
  
}

```

# -------------------------------------

# trend clustering

data from previous knn approach but has pairwise and susbets for all 6 spleen samples.

Use temporarily to make points in presentation, but will need to redo using all spleen samples eventually and not just PKHL

```{r}

load(file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/CODEX/brendan_R/20221101.spleen.trendClustering.knnApproach.Image.RData")

```

# pairwise of cell types of interest

```{r}

dat1 <- PKHL[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat1) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat1$sample <- "PKHL"

dat2 <- XXCD[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat2) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat2$sample <- "XXCD"

dat3 <- KSFB[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat3) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat3$sample <- "KSFB"

dat4 <- NGPL[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat4) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat4$sample <- "NGPL"

dat5 <- PBVN[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat5) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat5$sample <- "PBVN"

dat6 <- FSLD[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat6) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat6$sample <- "FSLD"


dat_spleen_pairwise <- dplyr::bind_rows(list(
  dat1,
  dat2,
  dat3,
  dat4,
  dat5,
  dat6
))

```

```{r}

cts <- c("Podoplanin", "CD4 Memory T cells", "Fol B cells")

dat <- dat_spleen_pairwise
dat <- dat[dat$reference %in% cts & dat$neighbor %in% cts & dat$sample == "PKHL",]

plotTrends(results = dat, idcol = "sample", figPath = paste0(figpath, "spleens.pkhl.pairwise.knnApproach.pdf"))

```

# subsets of cell types of interest

```{r}

dat1 <- PKHL_tpl[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat1) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat1$sample <- "PKHL"

dat2 <- XXCD_tpl[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat2) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat2$sample <- "XXCD"

dat3 <- KSFB_tpl[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat3) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat3$sample <- "KSFB"

dat4 <- NGPL_tpl[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat4) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat4$sample <- "NGPL"

dat5 <- PBVN_tpl[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat5) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat5$sample <- "PBVN"

dat6 <- FSLD_tpl[,c("refix", "neighix", "resolution", "zscore", "knn")]
colnames(dat6) <- c("reference", "neighbor", "resolution", "Z", "knn")
dat6$sample <- "FSLD"


dat_spleen_subsets <- dplyr::bind_rows(list(
  dat1,
  dat2,
  dat3,
  dat4,
  dat5,
  dat6
))

```

```{r}

cts_subset <- c("CD4 Memory T cells")

dat <- dat_spleen_subsets
dat <- dat[grepl(pattern = "Podoplanin_near_", x = dat_spleen_subsets$reference),]
# dat <- dat[dat$neighbor %in% cts_subset & dat$sample == "PKHL",]
dat <- dat[dat$neighbor %in% cts_subset,]

plotTrends(results = dat, idcol = "sample", figPath = paste0(figpath, "spleens.all.triplet.podosubs_vs_cd4_neigh.knnApproach.pdf"),
          width = 18, height = 5)

```

```{r}

cts_subset <- c("Podoplanin")

dat <- dat_spleen_subsets
dat <- dat[grepl(pattern = "CD4 Memory T cells_near_", x = dat_spleen_subsets$reference),]
dat <- dat[dat$neighbor %in% cts_subset & dat$sample == "PKHL",]

plotTrends(results = dat, idcol = "sample", figPath = paste0(figpath, "spleens.pkhl.triplet.cd4subs_vs_podo_neigh.knnApproach.pdf"),
          width = 18, height = 5)

```









