---
title: "Jean's simulation"
author: "Jean Fan"
date: "2/22/2023"
output:
  pdf_document: default
  html_document: default
---

```{r}
############# make new simulation
#library(ggplot2)

## cells
set.seed(1)
size <- 1000
x <- runif(size, min = 0, max = 10000)
y <- runif(size, min = 0, max = 10000)
p <- data.frame(x = x, y = y, type='D')
rownames(p) <- paste0('cell', 1:size)
head(p)
#ggplot(p, aes(x=x, y=y)) + geom_point(size=0.5) 

## structures
set.seed(10)
N <- 5 
as <- sample(x, N)
bs <- sample(y, N)
invisible(sapply(1:N, function(i) {
  a <- as[i]
  b <- bs[i]
  ro <- 1000
  co <- 'A'
  po <- 1
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))
#ggplot(p, aes(x=x, y=y,col=type)) + geom_point(size=0.5) 

invisible(sapply(1:N, function(i) {
  ro <- 500
  co <- 'B'
  po <- 1
  
  ## inside structure
  a <- as[i]
  b <- bs[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))

set.seed(1000)
M <- N*2
as2 <- sample(x, M)
bs2 <- sample(y, M)

invisible(sapply(1:M, function(i) {
  ro <- 500
  co <- 'B'
  po <- 1
  ## outside structure
  a <- as2[i]
  b <- bs2[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))
#ggplot(p, aes(x=x, y=y,col=type)) + geom_point(size=0.5) 

invisible(sapply(1:N, function(i) {
  ro <- 400
  co <- 'C'
  po <- 1
  
  ## inside structure
  a <- as[i]
  b <- bs[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))
#ggplot(p, aes(x=x, y=y,col=type)) + geom_point(size=0.5)

set.seed(10000)
as3 <- sample(x, M)
bs3 <- sample(y, M)
invisible(sapply(1:M, function(i) {
  ro <- 500
  co <- 'C'
  po <- 1
  ## outside structure
  a <- as3[i]
  b <- bs3[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))


plt <- crawdad::vizAllClusters(cells = p,
                               coms = p$type,
                               title = "sim",
                               axisAdj = 1, s = 6, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y")
plt
```
Actually using `crawdad`

## load library
```{r}
library(crawdad)
```

```{r}
## convert to SP
cells <- crawdad:::toSP(pos = p[,c("x", "y")],
                        celltypes = p$type)
plot(cells, pch=16)
```

```{r}
## generate background
shuffle.list <- crawdad:::makeShuffledCells(cells,
                        resolutions = c(250, 500, 1000, 3000, 5000, 10000),
                        perms = 1,
                        ncores = 7,
                        seed = 1,
                        verbose = TRUE)
```


## run pairwise
```{r}
## find trends, passing background as parameter
results <- crawdad::findTrends(cells,
                        dist = 250,
                        sub.type = "pairwise",
                        shuffle.list = shuffle.list,
                        perms = 1,
                        ncores = 7,
                        seed = 1, 
                        verbose = TRUE)
```

## plot
```{r}
## give users option to save
#crawdad::plotTrends(results = results, idcol = "dist")
crawdad::plotTrends(results = results["A"], idcol = "dist")
```

```{r}

binomMat <- crawdad::binomialTestMatrix(cells,
                               sub.dist = 1000,
                               ncores = 7,
                               verbose = TRUE)

```

```{r}

subset.list <- crawdad::selectSubsets(binomMat,
                             cells$celltypes,
                             sub.type = "near",
                             sub.thresh = 0.05,
                             ncores = 7,
                             verbose = TRUE)

```

visualize the subsets

```{r}

## make a temporary annotation factor with annotations for cells that are of a specific subsets
annots_temp <- crawdad::selectLabels(df = cells,
                                     com = cells$celltypes,
                                     subset_list = subset.list,
                                     cellIDs = c("A", "B", "C", "D"),
                                     subsetIDs = c("C_near_B"))

## visualize the subset only
plt <- crawdad::vizAllClusters(cells = cells,
                               coms = annots_temp,
                               ofInterest = c("C_near_B"),
                               title = "sim",
                               axisAdj = 1, s = 6, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y")
plt

```

visualize neighbors around a subset of cells

```{r}

neighCells <- getNeighbors(cells = cells,
                           reference.ids = subset.list[["C_near_B"]],
                           removeRef = TRUE,
                           dist = 1000)
neighCells

```

```{r}

## can add the neighbor cells to the list of cell subsets
subset.list[["C_near_B_neighs"]] <- rownames(neighCells)

```

```{r}

## make a temporary annotation factor with annotations for cells that are of a specific subsets
annots_temp <- crawdad::selectLabels(df = cells,
                                     com = cells$celltypes,
                                     subset_list = subset.list,
                                     cellIDs = c("A", "B", "C", "D"), ## original IDs in com of interest
                                     subsetIDs = c("C_near_B", "C_near_B_neighs") ## subsets in subset_list of interest
                                     )

## visualize just the cells in the subsets of interest
plt <- crawdad::vizAllClusters(cells = cells,
                               coms = annots_temp,
                               ofInterest = c("C_near_B", "C_near_B_neighs"), ## choose specific type to visualize
                               title = "sim",
                               axisAdj = 1, s = 6, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y")
plt

```

```{r}

## get the neighbor cells of a given subset (or cell type)
neighCells <- getNeighbors(cells = cells,
                           reference.ids = subset.list[["C_near_B"]],
                           removeRef = TRUE,
                           dist = 1000)

## make new data.frame with new cell labels column that marks non neighbors NA
pos <- spToDF(cells)
## make new column of cell type labels
pos$neighs <- pos$celltypes
## set the non neighbor cell labels to NA
non_neighbors <- setdiff(rownames(pos), rownames(neighCells))
pos[non_neighbors, "neighs"] <- NA
pos$neighs <- factor(pos$neighs)


## label the cells that are the specific subset that we originally were looking for neighbors
annots_temp <- crawdad::selectLabels(df = pos,
                                     com = pos$neighs,
                                     subset_list = subset.list,
                                     cellIDs = c("A", "B", "C", "D"), ## original IDs in com of interest
                                     subsetIDs = c("C_near_B") ## subsets in subset_list of interest
                                     )

## visualize the new data.frame with the temporary annotations that specifically labels the neighbor cells and the selected subset
plt <- crawdad::vizAllClusters(cells = pos,
                               coms = annots_temp,
                               title = "sim",
                               axisAdj = 1, s = 6, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y")
plt

```

visualize real vs shuffling, and then look at specific tiles to visualize

```{r}

## add new column of labels, now just plot
pos$shuff <- shuffle.list$`3000`$`1`

```

```{r}

## shuffling grid
grid <- sf::st_make_grid(cells, cellsize = 3000)

grid_coords <- as.data.frame(sf::st_coordinates(grid))

## centers of the grids to add the tile IDs
grid_coords_centroids <- as.data.frame(sf::st_coordinates(sf::st_centroid(grid)))
grid_coords_centroids$name <- as.character(rownames(grid_coords_centroids))

```

```{r}

plt <- crawdad::vizAllClusters(cells = pos,
                               coms = pos$celltypes,
                               title = "sim",
                               axisAdj = 1, s = 6, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y") +
  ggplot2::geom_sf(data = grid, fill = NA) +
  ggplot2::geom_text(data = grid_coords_centroids, ggplot2::aes(X, Y, label = name))
  
plt

```

```{r}

plt <- crawdad::vizAllClusters(cells = pos,
                               coms = pos$shuff,
                               title = "sim",
                               axisAdj = 1, s = 6, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y") +
  ggplot2::geom_sf(data = grid, fill = NA) +
  ggplot2::geom_text(data = grid_coords_centroids, ggplot2::aes(X, Y, label = name))
  
plt

```

```{r}

## pull out cells in specific grids
int <- sf::st_intersection(cells, grid[[11]])
pos2 <- pos[rownames(int),]

## grid 11 real
plt <- crawdad::vizAllClusters(cells = pos2,
                               coms = pos2$celltypes,
                               title = "grid 11",
                               axisAdj = 1, s = 10, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y")
  
plt

## grid 11 shuffled
plt <- crawdad::vizAllClusters(cells = pos2,
                               coms = pos2$shuff,
                               title = "grid 11",
                               axisAdj = 1, s = 10, a = 0.5) +
  ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2), ncol = 1)) +
  # ggplot2::theme(legend.position="none") +
  ggplot2::labs(x = "x",
                y = "y")
  
plt


```


```{r}
## bit confusing that findTrends for pairs and triplets are same
## what happens if you use the wrong sub.type parameter?
## anticipate user error
results2 <- crawdad::findTrends(cells,
                        dist = 250,
                        sub.type = "near",
                        shuffle.list = shuffle.list,
                        subset.list = subset.list,
                        perms = 1,
                        ncores = 7,
                        seed = 1, 
                        verbose = TRUE)
```

```{r}
## plot just some
crawdad::plotTrends(results = results2["C_near_B"], idcol = "dist")
```


