---
title: "2_seqfish"
author: "Brendan F. Miller"
date: "2/15/2023"
output: html_document
---

This vignette will go through analyses to reproduce the results and figures of the SeqFISH dataset.

```{r}

library(crawdad)
library(dplyr)

```

```{r}

ncores = 7

```

# Load data

```{r}

seq <- read.csv2(file = paste0(here::here(), "/data/seqfish/seqfish.meta.csv.gz"), row.names = 1, sep = ",")
seq <- seq[,c("x", "y", "cluster")]
## make sure the coordinates are numeric
seq <- seq %>%
  dplyr::mutate_at(vars(x, y), as.numeric)

## convert to SP
seq <- crawdad:::toSP(pos = seq[,c("x", "y")],
                        celltypes = seq$cluster)
seq

```

# Visualize celltypes

```{r, fig.height=24, fig.width=24}

crawdad::vizEachCluster(cells = seq,
                        coms = as.factor(seq$celltypes),
                        s = 2)

```

# Make shuffled background

```{r}

resolutions = c(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1200, 1500, 3000, 6000)

```

```{r}
## generate background
shuffle.list <- crawdad:::makeShuffledCells(seq,
                          resolutions = resolutions,
                          perms = 1,
                          ncores = ncores,
                          seed = 1,
                          verbose = TRUE)

## note: 0.77 minutes with 7 cores, 2.3 GHz Quad-Core Intel Core i7
```
save shuffled object
```{r, eval=FALSE}

saveRDS(shuffle.list, paste0(here::here(), "/data/seqfish/sp.seqfish.shuffled_res100-6000.rds"))

```

# Run pairwise analysis

```{r}

## find trends, passing background as parameter
results <- crawdad::findTrends(seq,
                        dist = 100,
                        shuffle.list = shuffle.list,
                        perms = 1,
                        ncores = ncores,
                        seed = 1, 
                        verbose = TRUE)

## note: 1.02 minutes with 7 cores, 2.3 GHz Quad-Core Intel Core i7

```

save pairwise results object
```{r, eval=FALSE}

saveRDS(results, paste0(here::here(), "/data/seqfish/sp.seqfish.pairwise.results.dist100.res100-6000.rds"))

## object with distances 50-300: sp.seqfish.pairwise.50-300.results.res100-6000.removeDups.rds

```

# Visualizing trends

```{r}

crawdad::plotTrends(results = results["Intermediate mesoderm"], idcol = "dist")

```

```{r}

crawdad::plotTrends(results = results["Endothelium"], idcol = "dist")

```

# Defining susbets

```{r}

binomMat <- crawdad::binomialTestMatrix(seq,
                               neigh.dist = 100,
                               ncores = ncores,
                               verbose = TRUE)

head(binomMat)

## note: 2.49 minutes with 7 cores, 2.3 GHz Quad-Core Intel Core i7
## previous code iteration on rockfish took 21 minutes with 32 cores! much better now 

```

```{r}

subset.list <- crawdad::selectSubsets(binomMat,
                             seq$celltypes,
                             sub.type = "near",
                             sub.thresh = 0.05,
                             ncores = ncores,
                             verbose = TRUE)

```

save the subsets
```{r, eval=FALSE}

saveRDS(subset.list, paste0(here::here(), "/data/seqfish/sp.seqfish.subsets.near.subdist100.rds"))

```

# Run analysis on subsets

```{r}

results.subsets <- crawdad::findTrends(seq,
                        dist = 100,
                        shuffle.list = shuffle.list,
                        subset.list = subset.list,
                        perms = 1,
                        ncores = ncores,
                        seed = 1, 
                        verbose = TRUE)

## note: 11.68 minutes with 7 cores, 2.3 GHz Quad-Core Intel Core i7; vs 7.53 minutes 14 cores on rockfish

```

save the results
```{r, eval=FALSE}

saveRDS(results.subsets, paste0(here::here(), "/data/seqfish/sp.seqfish.subset.results.dist100.res100-6000.rds"))

## sp.seqfish.triplet.near.binom.subdist100.dist100.results.res100-6000.removeDups.rds

```

# ---------------------------------
# Figures




