---
title: "pkhl dups, no dups"
author: "Brendan F. Miller"
date: "2/10/2023"
output: html_document
---

# imc

```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/squidpy/imc/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/squidpy/imc/"

```

```{r}

outfile <- paste0(dataDir, "sp.cooccuranceData.pairwise.results.10-300.withDups.rds")
dat1 <- readRDS(outfile)

dat1 <- meltResultsList(resultsList = dat1, id = NA)
colnames(dat1) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat1$dups <- TRUE

```

```{r}

outfile <- paste0(dataDir, "sp.cooccuranceData.pairwise.results.10-300.removeDups.rds")
dat2 <- readRDS(outfile)

dat2 <- meltResultsList(resultsList = dat2, id = NA)
colnames(dat2) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat2$dups <- FALSE

```

```{r}

dat <- rbind(dat1, dat2)

```

```{r}

plotTrends(results = dat1, idcol = "dist", figPath = paste0(figpath, "sp.imc.pairwise.dist10-300.withDups.pdf"),
          width = 40, height = 40)

```

```{r}

plotTrends(results = dat2, idcol = "dist", figPath = paste0(figpath, "sp.imc.pairwise.dist10-300.removeDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat[dat$dist == "10",]
plotTrends(results = d, idcol = "dups", figPath = paste0(figpath, "sp.imc.pairwise.dist10.dupsVsNoDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat[dat$dist == "30",]
plotTrends(results = d, idcol = "dups", figPath = paste0(figpath, "sp.imc.pairwise.dist30.dupsVsNoDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat1[dat1$dist == "10",]

plotTrendsOverlay(results = d, idcol = "dist", figPath = paste0(figpath, "sp.imc.pairwise.dist10.withDups.overlay.pdf"),
          width = 4, height = 40)

```


# slideseq

```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/slideseq/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/slide_seq/"

```

```{r}

outfile <- paste0(dataDir, "slideseqPuck.190926_08.rctd.pairwise.30-300.results.withDups.rds")
dat1 <- readRDS(outfile)

dat1 <- meltResultsList(resultsList = dat1, id = NA)
colnames(dat1) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat1$dups <- TRUE

```

```{r}

outfile <- paste0(dataDir, "slideseqPuck.190926_08.rctd.pairwise.30-300.results.removeDups.rds")
dat2 <- readRDS(outfile)

dat2 <- meltResultsList(resultsList = dat2, id = NA)
colnames(dat2) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat2$dups <- FALSE

```

```{r}

dat <- rbind(dat1, dat2)

```

```{r}

plotTrends(results = dat1, idcol = "dist", figPath = paste0(figpath, "slideseq.rctd.pairwise.dist30-300.withDups.pdf"),
          width = 40, height = 40)

```

```{r}

plotTrends(results = dat2, idcol = "dist", figPath = paste0(figpath, "slideseq.rctd.pairwise.dist30-300.removeDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat[dat$dist == "30",]
plotTrends(results = d, idcol = "dups", figPath = paste0(figpath, "slideseq.rctd.pairwise.dist30.dupsVsNoDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat2[dat2$dist == "30",]

plotTrendsOverlay(results = d, idcol = "dist", figPath = paste0(figpath, "slideseq.rctd.pairwise.dist30.removeDups.overlay.pdf"),
          width = 4, height = 40)

```


# pkhl

## pairwise

```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/spleen/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/results/pairwise/"

```

```{r}

outfile <- paste0(dataDir, "pkhl.pairwise.100-200.folBcombined.results.res100-6000.withDups.rds")
dat1 <- readRDS(outfile)

dat1 <- meltResultsList(resultsList = dat1, id = NA)
colnames(dat1) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat1$dups <- TRUE

```

```{r}

outfile <- paste0(dataDir, "pkhl.pairwise.100-200.folBcombined.results.res100-6000.removeDups.rds")
dat2 <- readRDS(outfile)

dat2 <- meltResultsList(resultsList = dat2, id = NA)
colnames(dat2) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat2$dups <- FALSE

```

```{r}

dat <- rbind(dat1, dat2)

```

```{r}

plotTrends(results = dat1, idcol = "dist", figPath = paste0(figpath, "pkhl.pairwise.100-200.results.res100-6000.withDups.pdf"),
          width = 40, height = 40)

```

```{r}

plotTrends(results = dat2, idcol = "dist", figPath = paste0(figpath, "pkhl.pairwise.100-200.results.res100-6000.removeDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat[dat$dist == "100",]

plotTrends(results = d, idcol = "dups", figPath = paste0(figpath, "pkhl.pairwise.d100.results.res100-6000.dupsVsNoDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat2[dat2$dist == "100",]

plotTrendsOverlay(results = d, idcol = "dist", figPath = paste0(figpath, "pkhl.pairwise.d100.removeDups.overlay.pdf"),
          width = 4, height = 40)

```

## triplets

```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/spleen/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/results/triplet/"

```

```{r}

outfile <- paste0(dataDir, "pkhl.triplet.near.binom.subdist100.dist100.folBcombined.results.res100-6000.withDups.rds")
dat1 <- readRDS(outfile)

dat1 <- meltResultsList(resultsList = dat1, id = NA)
colnames(dat1) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat1$subdist <- "100"
dat1$dups <- TRUE

```

```{r}

outfile <- paste0(dataDir, "pkhl.triplet.near.binom.subdist100.dist100.folBcombined.results.res100-6000.removeDups.rds")
dat2 <- readRDS(outfile)

dat2 <- meltResultsList(resultsList = dat2, id = NA)
colnames(dat2) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat2$subdist <- "100"
dat2$dups <- FALSE

```

```{r}

dat <- rbind(dat1, dat2)

```

```{r}

d <- dat2[grepl(pattern = "CD4 Memory T cells_near_", x = dat2$reference),]

plotTrends(results = d, idcol = "dist", figPath = paste0(figpath, "pkhl.cd4_near.d100.subd100.results.res100-6000.removeDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat2[grepl(pattern = "Podoplanin_near_", x = dat2$reference),]

plotTrends(results = d, idcol = "dist", figPath = paste0(figpath, "pkhl.podo_near.d100.subd100.results.res100-6000.removeDups.pdf"),
          width = 40, height = 40)

```

```{r}

d <- dat2[grepl(pattern = "Fol B cells_near_", x = dat2$reference),]

plotTrends(results = d, idcol = "dist", figPath = paste0(figpath, "pkhl.folb_near.d100.subd100.results.res100-6000.removeDups.pdf"),
          width = 40, height = 40)

```



```{r}

d <- dat2[grepl(pattern = "Fol B cells_near_", x = dat2$reference),]
d <- d[d$neighbor %in% c("CD4 Memory T cells", "Fol B cells", "Podoplanin"),]

plotTrendsOverlay(results = d, idcol = "dist", figPath = paste0(figpath, "pkhl.folb_subs.d100.subd100.removeDups.cd4_podo_folb.overlay.pdf"),
          width = 4, height = 40)

```

```{r}

d <- dat2[grepl(pattern = "Podoplanin_near_", x = dat2$reference),]
d <- d[d$neighbor %in% c("CD4 Memory T cells", "Fol B cells", "Podoplanin"),]

plotTrendsOverlay(results = d, idcol = "dist", figPath = paste0(figpath, "pkhl.podo_subs.d100.subd100.removeDups.cd4_podo_folb.overlay.pdf"),
          width = 4, height = 40)

```

```{r}

d <- dat2[grepl(pattern = "CD4 Memory T cells_near_", x = dat2$reference),]
d <- d[d$neighbor %in% c("CD4 Memory T cells", "Fol B cells", "Podoplanin"),]

plotTrendsOverlay(results = d, idcol = "dist", figPath = paste0(figpath, "pkhl.cd4_subs.d100.subd100.removeDups.cd4_podo_folb.overlay.pdf"),
          width = 4, height = 40)

```


# seqfish

## pairwise

```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/squidpy/seqfish/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/squidpy/seqfish/"

```

```{r}

outfile <- paste0(dataDir, "sp.seqfish.pairwise.50-300.results.res100-6000.removeDups.rds")
dat1 <- readRDS(outfile)

dat1 <- meltResultsList(resultsList = dat1, id = NA)
colnames(dat1) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat1$dups <- FALSE

plotTrends(results = dat1, idcol = "dist", figPath = paste0(figpath, "sp.seqfish.pairwise.50-300.results.res100-6000.removeDups.pdf"),
          width = 50, height = 50)

```

```{r}

d <- dat1[dat1$dist == "100",]

plotTrendsOverlay(results = d, idcol = "dist", figPath = paste0(figpath, "sp.seqfish.pairwise.dist100.removeDups.overlay.pdf"),
          width = 4, height = 50)

```
