---
title: "Jean's simulation"
author: "Jean Fan"
date: "2/22/2023"
output:
  pdf_document: default
  html_document: default
---

```{r}
############# make new simulation
library(ggplot2)

## cells
set.seed(1)
size <- 6000
x <- runif(size, min = 0, max = 10000)
y <- runif(size, min = 0, max = 10000)
p <- data.frame(x = x, y = y, type=sample(c('D', 'E'), size, replace=TRUE))
rownames(p) <- paste0('cell', 1:size)
head(p)
ggplot(p, aes(x=x, y=y)) + geom_point(size=0.5) 

## structures
set.seed(10)
N <- 5 
as <- sample(x, N)
bs <- sample(y, N)
invisible(sapply(1:N, function(i) {
  a <- as[i]
  b <- bs[i]
  ro <- 1000
  co <- 'A'
  po <- 1
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))
ggplot(p, aes(x=x, y=y,col=type)) + geom_point(size=0.5) 

invisible(sapply(1:N, function(i) {
  ro <- 500
  co <- 'B'
  po <- 1
  
  ## inside structure
  a <- as[i]
  b <- bs[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))

set.seed(1000)
M <- N*2
as2 <- sample(x, M)
bs2 <- sample(y, M)

invisible(sapply(1:M, function(i) {
  ro <- 500
  co <- 'B'
  po <- 1
  ## outside structure
  a <- as2[i]
  b <- bs2[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))
ggplot(p, aes(x=x, y=y,col=type)) + geom_point(size=0.5) 

invisible(sapply(1:N, function(i) {
  ro <- 400
  co <- 'C'
  po <- 1
  
  ## inside structure
  a <- as[i]
  b <- bs[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))
ggplot(p, aes(x=x, y=y,col=type)) + geom_point(size=0.5)

set.seed(10000)
as3 <- sample(x, M)
bs3 <- sample(y, M)
invisible(sapply(1:M, function(i) {
  ro <- 500
  co <- 'C'
  po <- 1
  ## outside structure
  a <- as3[i]
  b <- bs3[i]
  c1o <- rownames(p[((p$x-a)^2 + (p$y - b)^2 < ro^2),])
  p[c1o,]$type <<- sample(co, size = length(c1o), replace = TRUE, prob = po)
}))
ggplot(p, aes(x=x, y=y,col=type)) + geom_point(size=0.5) 
```

## load library
```{r}
library(crawdad)
```
## run pairwise
```{r}
results <- crawdad::findTrends(pos = p[,c("x", "y")],
                        celltypes = p$type,
                        resolutions = c(250, 500, 1000, 3000, 5000, 10000),
                        dist = 250,
                        sub.type = "pairwise",
                        perms = 1,
                        ncores = 10,
                        verbose = FALSE,
                        saveShuffleFile = 'test.rds',
                        seed = 1)

## should have printable plot
## give users option to save plot via
## pdf() or png() and dev.off()
crawdad::plotTrends(results = results, idcol = "dist", legend = FALSE,
           figPath = "test.pdf",
           width = 10, height = 10)
```

```{r}
##### How to do subsets? Do not seem to have good functions yet
pos <- p[,1:2]
celltypes <- as.factor(p[,3])
## should have function to make this conversion once 
## and reuse output across functions
## rather than putting it in findTrends()
cells <- sp::SpatialPointsDataFrame(
  coords = as.data.frame(pos),
  data = data.frame(
    celltypes = celltypes
  ))
cells <- sf::st_as_sf(cells)
rownames(cells) <- as.character(1:dim(cells)[1])
sf::st_agr(cells) <- "constant"
plot(cells, pch=16)

```

```{r}
##### get subsets
## note I can choose to save the output
## or I should be able to just pass subset.list as a parameter
## rather than forcing me to save and load from a file
##### also currently not exported so using :::
subset.list <- crawdad:::getSubsets(cells = cells,
                          sub.dist = 250,
                          sub.type = "near",
                          sub.thresh = 0.05,
                          ncores = 10,
                          verbose = FALSE)
saveRDS(subset.list, file='subset.rds')
```

```{r}
## bit confusing that findTrends for pairs and triplets are same
## what happens if you use the wrong sub.type parameter?
## anticipate user error
results2 <- crawdad::findTrends(pos = p[,c("x", "y")],
                        celltypes = p$type,
                        resolutions = c(250, 500, 1000, 3000, 5000, 10000),
                        dist = 250,
                        sub.type = "near",
                        perms = 1,
                        ncores = 10,
                        verbose = TRUE,
                        loadShuffleFile = 'test.rds',
                        loadSubsetFile ='subset.rds',
                        seed = 1)
```

```{r}
## issue has Nans because some cells not ever found near each other
## ideally should be ignored when plotting
## currently hack fix by setting to 0
results2.fixed <- lapply(results2, function(x) {
  x[is.nan(x)] <- 0
  return(x)
})

## plot
crawdad::plotTrends(results = results2.fixed, idcol = "dist", legend = FALSE,
           figPath = "test2.pdf",
           width = 50, height = 50)
```
