---
title: "Untitled"
author: "Brendan F. Miller"
date: "11/9/2022"
output: html_document
---


simple code to convert the Seurat format CODEX datasets into CSV files stored in the data folder

(note that this iteration makes the column names consistent between all datasets; also shortened the sample names to just the 4 letter codes for simplicity)

```{r}

m <- HBM389.PKHL.936@meta.data[,c("x", "y", "com_nn50_VolnormExpr_data_annots", "com_nn50_VolnormExpr_data_annots_bcombn")]
colnames(m) <- c("x", "y", "celltypes", "celltypes_folBcombined")
write.csv2(x = m, file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/PKHL.meta.csv", row.names = TRUE)


m <- HBM772.XXCD.697@meta.data[,c("x", "y", "com_nn50_VolnormExpr_data_annots_byPKHL", "com_nn50_VolnormExpr_data_annots_byPKHL_bcombn")]
colnames(m) <- c("x", "y", "celltypes", "celltypes_folBcombined")
write.csv2(x = m, file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/XXCD.meta.csv", row.names = TRUE)

```

```{r}

m <- HBM556.KSFB.592@meta.data[,c("x", "y", "com_nn50_VolnormExpr_data_annots_byPKHL", "com_nn50_VolnormExpr_data_annots_byPKHL_bcombn")]
colnames(m) <- c("x", "y", "celltypes", "celltypes_folBcombined")
write.csv2(x = m, file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/KSFB.meta.csv", row.names = TRUE)

m <- HBM568.NGPL.345@meta.data[,c("x", "y", "com_nn50_VolnormExpr_data_annots_byKSFBharmonized", "com_nn50_VolnormExpr_data_annots_byKSFBharmonized_bcombn")]
colnames(m) <- c("x", "y", "celltypes", "celltypes_folBcombined")
write.csv2(x = m, file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/NGPL.meta.csv", row.names = TRUE)

```

```{r}

m <- HBM825.PBVN.284@meta.data[,c("x", "y", "com_nn50_VolnormExpr_data_annots_byPKHL", "com_nn50_VolnormExpr_data_annots_byPKHL_bcombn")]
colnames(m) <- c("x", "y", "celltypes", "celltypes_folBcombined")
write.csv2(x = m, file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/PBVN.meta.csv", row.names = TRUE)


m <- HBM342.FSLD.938@meta.data[,c("x", "y", "com_nn50_VolnormExpr_data_annots_byPBVNharmonized", "com_nn50_VolnormExpr_data_annots_byPBVNharmonized_bcombn")]
colnames(m) <- c("x", "y", "celltypes", "celltypes_folBcombined")
write.csv2(x = m, file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/FSLD.meta.csv", row.names = TRUE)

```

how to read them back in:

```{r}

# n <- read.csv2(file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/PKHL.meta.csv.gz", row.names = 1)

```

