---
title: "Untitled"
author: "Brendan F. Miller"
date: "2/3/2023"
output: html_document
---

```{r}

locs <- list(
  c(0.5, 0.5)
  )

cts <- list(
  list(outer = "B", inner = c("C"))
  )

probs <- list(
  list(outer = c(1), inner = c(1))
  )

## background params
s <- 10000
cb <- c("A")
pb <- c(1)

rads <- replicate(4, list(outer = 0.15, inner = 0.05), simplify=FALSE)
pos_300 <- simulate_circles(simulate_background(size = s, cts = cb, prob = pb),
                        locs, radii = rads, cts, probs)

```

```{r}

ggplot2::ggplot(data = pos_300) +
  ggplot2::geom_point(ggplot2::aes(x = x, y = y, color = type)) +
  ggplot2::scale_color_discrete() +
  ggplot2::coord_equal()

```

```{r}

pos <- pos_300[,c("x", "y")] * 3100
celltypes <- pos_300$type

cells <- sp::SpatialPointsDataFrame(
  coords = as.data.frame(pos),
  data=data.frame(
    celltypes=celltypes
    #name=rownames(pos)
  ))
cells <- sf::st_as_sf(cells)

## Change rowname assignments of cells to integers.
## Solution to keep rows in same order later on when
## randomly shuffling cell labels
rownames(cells) <- as.character(1:dim(cells)[1])

# make asumption that cell type attribute is constant throughout the geometries of each cell
## it removed the warning that keep popping up, which says this assumption is made anyways
sf::st_agr(cells) <- "constant"

```

```{r}

resolutions <- c(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1200, 1500, 3000, 3100)

randomcellslist <- makeShuffledCells(cells,
                                     resolutions,
                                     perms = 1,
                                     ncores = 7,
                                     seed = 1,
                                     verbose = TRUE)

```

```{r}

d <- 50
ct <- "B"

ref.buffer <- sf::st_buffer(cells[cells$celltypes == ct,], d)
neigh.cells <- sf::st_intersection(cells, ref.buffer$geometry)

```

```{r}

cells[cells$celltypes == ct,]

```


```{r}

ref.buffer

```

```{r}

neigh.cells

```

```{r}

rownames(neigh.cells)

```

```{r}

neigh.cells[intersect(rownames(neigh.cells), rownames(cells)),]

```

```{r}

pos_300

```

```{r}

write.csv(pos_circSubset[,c("x", "y", "type")], file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/sim/oneCircle.subsets.meta.csv", sep = ",")

```

```{r}



```


```{r}

sim <- read.csv2(file = "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/sim/simPairwise.meta.csv", row.names = 1, sep=",")

```

```{r}

ggplot2::ggplot(data = sim) +
  ggplot2::geom_point(ggplot2::aes(x = x, y = y, color = type)) +
  ggplot2::scale_color_discrete() +
  ggplot2::coord_equal()

```


# slide seq rctd

```{r}

dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/slide_seq/"
figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/slideseq/"

```

```{r}

outfile <- paste0(dataDir, "slideseqPuck.190926_08.rctd.pairwise.30-300.results.rds")
dat <- readRDS(outfile)

dat1 <- meltResultsList(resultsList = dat, id = NA)
colnames(dat1) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat1$dups <- TRUE

```

```{r}

outfile <- paste0(dataDir, "slideseqPuck.190926_08.rctd.pairwise.30-300.results.removeDupNeighs.rds")
dat <- readRDS(outfile)

dat2 <- meltResultsList(resultsList = dat, id = NA)
colnames(dat2) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat2$dups <- FALSE

```

```{r}

dat <- rbind(dat1, dat2)

```

```{r}

dat <- dat[dat$dist %in% c("200"),]
dat <- dat[dat$resolution %in% c(50,100,200,300,500,700,800,900,1000,1200,1500,3000,6000),]

plotTrends(results = dat, idcol = "dups", figPath = paste0(figpath, "slideseqPuck.190926_08.rctd.pairwise.d200.neighDupVsRemoveDup.pdf"),
          width = 35, height = 35)

```

# squidpy slideseq

```{r}

dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/squidpy/"
figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/squidpy/"

```

```{r}

outfile <- paste0(dataDir, "sp.slideseqv2.pairwise.30-300.results.rds")
dat <- readRDS(outfile)

dat1 <- meltResultsList(resultsList = dat, id = NA)
colnames(dat1) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat1$dups <- TRUE

```

```{r}

outfile <- paste0(dataDir, "sp.slideseqv2.pairwise.30-300.results.removeDupNeighs.rds")
dat <- readRDS(outfile)

dat2 <- meltResultsList(resultsList = dat, id = NA)
colnames(dat2) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat2$dups <- FALSE

```

```{r}

dat <- rbind(dat1, dat2)

```

```{r}

dat <- dat[dat$dist %in% c("200"),]
dat <- dat[dat$resolution %in% c(50,100,200,300,500,700,800,900,1000,1200,1500,3000,6000),]

plotTrends(results = dat, idcol = "dups", figPath = paste0(figpath, "sp.slideseqv2.pairwise.d200.neighDupVsRemoveDup.pdf"),
          width = 35, height = 35)

```


# ----------------------------------

# pkhl remove dups


```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/joint_meeting_figs/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/results/pairwise/"

outfile <- paste0(dataDir, "pkhl.pairwise.50-200.results.removeDupNeighs.rds")
dat <- readRDS(outfile)

dat <- meltResultsList(resultsList = dat, id = NA)
colnames(dat) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat <- dat[dat$resolution %in% c(100,200,300,500,600,700,800,900,1000,1200,1500,3000),]
dat$dups <- FALSE


outfile <- paste0(dataDir, "pkhl.pairwise.results.rds")
dat2 <- readRDS(outfile)

dat2 <- meltResultsList(resultsList = dat2, id = NA)
colnames(dat2) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat2 <- dat2[dat2$dist %in% c("100", "200"),]
dat2 <- dat2[dat2$resolution %in% c(100,200,300,500,600,700,800,900,1000,1200,1500,3000),]
dat2$dups <- TRUE

dat <- rbind(dat, dat2)



dat <- dat[dat$dist %in% c("200"),]

plotTrends(results = dat, idcol = "dups", figPath = paste0(figpath, "pkhl.pairwise.d200.neighDupVsRemoveDup.pdf"),
          width = 40, height = 40)

```

```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/joint_meeting_figs/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/results/pairwise/"

outfile <- paste0(dataDir, "pkhl.pairwise.50-200.results.removeDupNeighs.rds")
dat <- readRDS(outfile)

dat <- meltResultsList(resultsList = dat, id = NA)
colnames(dat) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat <- dat[dat$resolution %in% c(100,200,300,500,600,700,800,900,1000,1200,1500,3000),]
dat$dups <- FALSE

plotTrends(results = dat, idcol = "dist", figPath = paste0(figpath, "pkhl.pairwise.d100-200.RemoveDups.pdf"),
          width = 40, height = 40)

```

```{r}

figpath <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/plots/joint_meeting_figs/"
dataDir <- "/Users/brendan/Desktop/PostDoc/work/HuBMAP/repos/multiscale_celltype_colocalization_analysis/data/temp/results/pairwise/"

outfile <- paste0(dataDir, "pkhl.pairwise.100-200.folBcombined.results.removeDupNeighs.rds")
dat <- readRDS(outfile)

dat <- meltResultsList(resultsList = dat, id = NA)
colnames(dat) <- c("resolution", "neighbor", "Z", "reference", "dist", "dups")

dat <- dat[dat$resolution %in% c(100,200,300,500,600,700,800,900,1000,1200,1500,3000),]
dat$dups <- FALSE

plotTrends(results = dat, idcol = "dist", figPath = paste0(figpath, "pkhl.pairwise.d100-200.folBcombined.RemoveDups.pdf"),
          width = 40, height = 40)

```













