---
title: "seqFISH Analysis"
author: 
- "Rafael dos Santos Peixoto"
- "Brendan F. Miller"
date: "10/02/2023"
# output: rmarkdown::html_document
output:
  md_document:
    variant: markdown_github
vignette: >
  %\VignetteIndexEntry{seqFISH analysis}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

This vignette will go through analyses to reproduce the results and figures of a mouse embryo SeqFISH dataset.

```{r}

library(crawdad)
library(tidyverse)

```

```{r}

ncores = 7

```

# Load data

```{r, warning=FALSE}

data(seq)

## invert coordinates
seq$y <- -seq$y

## convert to sf
seq <- crawdad:::toSF(pos = seq[,c("x", "y")],
                        celltypes = seq$celltypes)

```

# Visualize celltypes

```{r celltypes, warning=FALSE, message=FALSE, fig.height=24, fig.width=24}

crawdad::vizEachCluster(cells = seq,
                        coms = as.factor(seq$celltypes),
                        s = 2)

```

# Make shuffled background

```{r}

scales <- seq(100, 1000, by=100)

```

```{r, warning=FALSE}

## generate background
shuffle.list <- crawdad:::makeShuffledCells(seq,
                          scales = scales,
                          perms = 3,
                          ncores = ncores,
                          seed = 1,
                          verbose = TRUE)

## note: 1.94 minutes with 7 M2 cores

```

# Run pairwise analysis

```{r, warning=FALSE}

## find trends, passing background as parameter
results <- crawdad::findTrends(seq,
                        dist = 100,
                        shuffle.list = shuffle.list,
                        ncores = ncores,
                        verbose = TRUE,
                        returnMeans = FALSE)

## note: 1.73 minutes with 7 M2 cores

```

```{r}

## convert results to data.frame
dat <- crawdad::meltResultsList(results, withPerms = T)

```


# Visualize results

```{r}

## multiple-test correction
ntests <- length(unique(dat$reference)) * length(unique(dat$reference))
psig <- 0.05/ntests
zsig <- round(qnorm(psig/2, lower.tail = F), 2)

```

Summary visualization of CRAWDAD’s multi-scale cell-type spatial relationship analysis.

```{r colocalization, fig.height=9, fig.width=11}

vizColocDotplot(dat, reorder = TRUE, zsig.thresh = zsig, zscore.limit = zsig*2) +
  theme(legend.position='right',
        axis.text.x = element_text(angle = 45, h = 0))

```

Visualize specific trends.

```{r endo_haematoprog}

dat_filter <- dat %>% 
  filter(reference == 'Endothelium') %>% 
  filter(neighbor == 'Haematoendothelial progenitors')
vizTrends(dat_filter, lines = T, withPerms = T, sig.thresh = zsig)

```

```{r intermeso_latmeso}

dat_filter <- dat %>% 
  filter(reference == 'Intermediate mesoderm') %>% 
  filter(neighbor == 'Lateral plate mesoderm')
vizTrends(dat_filter, lines = T, withPerms = T, sig.thresh = zsig)

```
